const API_LOGIN_REQUEST = 'API_LOGIN_REQUEST';
const API_LOGIN_SUCCESS = 'API_LOGIN_SUCCESS';
const API_LOGIN_FAILURE = 'API_LOGIN_FAILURE';

export {
    API_LOGIN_REQUEST,
    API_LOGIN_SUCCESS,
    API_LOGIN_FAILURE,
};
